services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LiquidLight\Anthology\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  LiquidLight\Anthology\Hook\PluginConfigurationHook:
    public: true
