services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LiquidLight\Anthology\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  cache.llanthology_cache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['llanthology_cache']

  LiquidLight\Anthology\Factory\RepositoryFactory:
    public: true
    arguments:
      $cache: '@cache.llanthology_cache'

  LiquidLight\Anthology\Factory\FilterFactory:
    public: true
    arguments:
      $cache: '@cache.llanthology_cache'

  LiquidLight\Anthology\EventListener\CacheWarmupEventListener:
    public: true
    arguments:
      $cache: '@cache.llanthology_cache'

  LiquidLight\Anthology\Hook\PluginConfigurationHook:
    public: true

  LiquidLight\Anthology\Hook\FilterConfigurationHook:
    public: true
